In [23]:
import pandas as pd

In [24]:
df = pd.read_csv("../data/raw_clinical_trials.csv")

print(df.shape)
df.head()

(1000, 11)

,NCT Number,Study Title,Study Status,Brief Summary,Conditions,Interventions,Sponsor,Phases,Start Date,Completion Date,Locations
0,NCT07048990,Feasibility of Empowerment Group Therapy on Uk...,RECRUITING,This single-arm pilot study aims to explore th...,Depression NOS,BEHAVIORAL: Empowerment Group Therapy,"Charite University, Berlin, Germany",NaN,2024-11-05,2025-09,"National Medical University Bogomolets, Kyiv, ..."
1,NCT02958527,Drug Use Investigation Of Effexor (SECONDARY D...,COMPLETED,SECONDARY DATA COLLECTION STUDY; SAFETY AND EF...,Depression/Depressed State,DRUG: venlafaxine,Pfizer's Upjohn has merged with Mylan to form ...,NaN,2016-10-03,2020-05-11,NaN
2,NCT03278938,"Add-on to Cognitive, Event-Related Potentials ...",WITHDRAWN,Depressed patients unremitted after monotherap...,Depressive Illness,DRUG: bupropion|DRUG: citalopram,New York State Psychiatric Institute,PHASE4,2012-06-29,2016-01,"New York State Psychiatric Institute, New York..."
3,NCT07528014,ATLAS-1: Advanced Trial for Longitudinal Asses...,RECRUITING,This study will evaluate the feasibility and c...,Depressed Mood,NaN,"Salma Health, Inc.",NaN,2026-03-25,2037-03,"Salma Health, La Jolla, California, 92037, Uni..."
4,NCT03966833,Using Group Interpersonal Psychotherapy to Imp...,COMPLETED,Adolescent girls in developing countries face ...,Mental Depression,BEHAVIORAL: IPT-G|BEHAVIORAL: Unconditional Ca...,George Washington University,NaN,2019-05-26,2022-09-30,"BRAC Uganda, Kampala, Uganda"

In [25]:
df.columns

Index(['NCT Number', 'Study Title', 'Study Status', 'Brief Summary',
       'Conditions', 'Interventions', 'Sponsor', 'Phases', 'Start Date',
       'Completion Date', 'Locations'],
      dtype='object')

In [26]:
df_base = df[
    [
        "NCT Number",
        "Study Title",
        "Study Status",
        "Conditions",
        "Interventions",
        "Sponsor",
        "Phases",
        "Locations",
        "Start Date",
        "Completion Date"
    ]
].copy()

df_base.head()
# print(df_base.shape) -> 1000,10

,NCT Number,Study Title,Study Status,Conditions,Interventions,Sponsor,Phases,Locations,Start Date,Completion Date
0,NCT07048990,Feasibility of Empowerment Group Therapy on Uk...,RECRUITING,Depression NOS,BEHAVIORAL: Empowerment Group Therapy,"Charite University, Berlin, Germany",NaN,"National Medical University Bogomolets, Kyiv, ...",2024-11-05,2025-09
1,NCT02958527,Drug Use Investigation Of Effexor (SECONDARY D...,COMPLETED,Depression/Depressed State,DRUG: venlafaxine,Pfizer's Upjohn has merged with Mylan to form ...,NaN,NaN,2016-10-03,2020-05-11
2,NCT03278938,"Add-on to Cognitive, Event-Related Potentials ...",WITHDRAWN,Depressive Illness,DRUG: bupropion|DRUG: citalopram,New York State Psychiatric Institute,PHASE4,"New York State Psychiatric Institute, New York...",2012-06-29,2016-01
3,NCT07528014,ATLAS-1: Advanced Trial for Longitudinal Asses...,RECRUITING,Depressed Mood,NaN,"Salma Health, Inc.",NaN,"Salma Health, La Jolla, California, 92037, Uni...",2026-03-25,2037-03
4,NCT03966833,Using Group Interpersonal Psychotherapy to Imp...,COMPLETED,Mental Depression,BEHAVIORAL: IPT-G|BEHAVIORAL: Unconditional Ca...,George Washington University,NaN,"BRAC Uganda, Kampala, Uganda",2019-05-26,2022-09-30

In [27]:
df_base = df_base.rename(columns={
    "NCT Number" : "nct_id",
"Study Title" : "study_title",
"Study Status"  :"study_status",
"Conditions" : "conditions",
"Interventions" : "interventions",
"Sponsor" : "sponsor",
"Phases" : "phases",
"Location" : "locations",
"Start Date" : "start_date",
"Completion Date" : "completion_date"
})

df_base.head()

,nct_id,study_title,study_status,conditions,interventions,sponsor,phases,Locations,start_date,completion_date
0,NCT07048990,Feasibility of Empowerment Group Therapy on Uk...,RECRUITING,Depression NOS,BEHAVIORAL: Empowerment Group Therapy,"Charite University, Berlin, Germany",NaN,"National Medical University Bogomolets, Kyiv, ...",2024-11-05,2025-09
1,NCT02958527,Drug Use Investigation Of Effexor (SECONDARY D...,COMPLETED,Depression/Depressed State,DRUG: venlafaxine,Pfizer's Upjohn has merged with Mylan to form ...,NaN,NaN,2016-10-03,2020-05-11
2,NCT03278938,"Add-on to Cognitive, Event-Related Potentials ...",WITHDRAWN,Depressive Illness,DRUG: bupropion|DRUG: citalopram,New York State Psychiatric Institute,PHASE4,"New York State Psychiatric Institute, New York...",2012-06-29,2016-01
3,NCT07528014,ATLAS-1: Advanced Trial for Longitudinal Asses...,RECRUITING,Depressed Mood,NaN,"Salma Health, Inc.",NaN,"Salma Health, La Jolla, California, 92037, Uni...",2026-03-25,2037-03
4,NCT03966833,Using Group Interpersonal Psychotherapy to Imp...,COMPLETED,Mental Depression,BEHAVIORAL: IPT-G|BEHAVIORAL: Unconditional Ca...,George Washington University,NaN,"BRAC Uganda, Kampala, Uganda",2019-05-26,2022-09-30

In [28]:
df_base.to_csv("../data/cleaned_base.csv", index=False, encoding="utf-8-sig")