In [1]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("../data/clinical_trials.db")

In [2]:
query = """
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT nct_id) AS unique_trials,
    COUNT(DISTINCT sponsor) AS unique_sponsors
FROM clinical_trials;
"""

summary = pd.read_sql_query(query, conn)
summary

   total_rows  unique_trials  unique_sponsors
0        1000           1000              505

In [3]:
query = """
SELECT
    study_status,
    COUNT(*) AS trial_count
FROM clinical_trials
GROUP BY study_status
ORDER BY trial_count DESC;
"""

status_result = pd.read_sql_query(query, conn)
status_result

              study_status  trial_count
0                COMPLETED          605
1                  UNKNOWN          151
2               RECRUITING           94
3               TERMINATED           53
4       NOT_YET_RECRUITING           35
5                WITHDRAWN           28
6    ACTIVE_NOT_RECRUITING           24
7                SUSPENDED            5
8  ENROLLING_BY_INVITATION            5

In [4]:
query = """
SELECT
    COALESCE(phases, 'NO_PHASE') AS phase,
    COUNT(*) AS trial_count
FROM clinical_trials
GROUP BY COALESCE(phases, 'NO_PHASE')
ORDER BY trial_count DESC;
"""

phase_result = pd.read_sql_query(query, conn)
phase_result

           phase  trial_count
0       NO_PHASE          729
1         PHASE4           88
2         PHASE2           68
3         PHASE3           40
4         PHASE1           29
5  PHASE2|PHASE3           18
6   EARLY_PHASE1           16
7  PHASE1|PHASE2           12

In [5]:
query = """
SELECT
    sponsor,
    COUNT(*) AS trial_count
FROM clinical_trials
WHERE sponsor IS NOT NULL
GROUP BY sponsor
ORDER BY trial_count DESC
LIMIT 10;
"""

sponsor_result = pd.read_sql_query(query, conn)
sponsor_result

                                       sponsor  trial_count
0               Massachusetts General Hospital           29
1                     University of Pittsburgh           18
2  Weill Medical College of Cornell University           16
3   National Institute of Mental Health (NIMH)           16
4                          Stanford University           15
5        University of California, Los Angeles           14
6      University of California, San Francisco           12
7                      Northwestern University           12
8              Chinese University of Hong Kong           12
9         New York State Psychiatric Institute           11

In [6]:
conn.close()