In [1]:
import pandas as pd

In [2]:
path = "../data/raw_anxiety_trials.csv"

In [4]:
anxiety_df = pd.read_csv(path)

In [6]:
anxiety_df.shape

(1000, 11)

In [7]:
anxiety_df.head()

,NCT Number,Study Title,Study Status,Brief Summary,Conditions,Interventions,Sponsor,Phases,Start Date,Completion Date,Locations
0,NCT06150612,Unwinding Anxiety for Migraine: Pilot,UNKNOWN,This is a pilot study that aims to understand ...,Migraine|Anxiousness,BEHAVIORAL: Unwinding Anxiety,Yeshiva University,NaN,2024-01-03,2025-01-01,"Rousso Building, The Bronx, New York, 10461, U..."
1,NCT01675986,Comparing the Efficacy of Pregabalin and Hydro...,COMPLETED,The insertion of long-lasting intravenous devi...,Feeling Anxious,DRUG: hydroxyzine|DRUG: Pregabalin|DRUG: Lactose,Poitiers University Hospital,PHASE2,NaN,NaN,"CHU de POITIERS, Poitiers, 86021, France"
2,NCT03425487,Mindfulness-based and Compassion-based Interve...,COMPLETED,The aim of this study is to assess and compare...,Anxious-Depressive,BEHAVIORAL: Mindfulness based Intervention|BEH...,Hospital Miguel Servet,NaN,2019-01-01,2019-10-31,"Hospital Universitario de la Plana, Castellon,..."
3,NCT06921512,TCM Daoyin for Anxiety/Depression: Psychologic...,RECRUITING,This 12-week single-arm clinical trial investi...,Anxiety Symptom|Depression Symptom,BEHAVIORAL: TCM Daoyin exercise,Shanghai University of Traditional Chinese Med...,NaN,2025-04-10,2027-09-30,"Shanghai Qigong Research Institute, Shanghai, ..."
4,NCT06350201,Machine Learning-based Classification of Sympt...,RECRUITING,"To breakthrough the bottleneck identified, we ...",Depression and Anxiety Symptom,BEHAVIORAL: problem solving therapy|OTHER: con...,Wuhan Mental Health Centre,NaN,2025-09-01,2026-12-01,"Renmin Hospital of Wuhan University, Wuhan, China"

In [37]:
anxiety_df.columns.tolist()

['NCT Number',
 'Study Title',
 'Study Status',
 'Brief Summary',
 'Conditions',
 'Interventions',
 'Sponsor',
 'Phases',
 'Start Date',
 'Completion Date',
 'Locations']

In [38]:
# 컬럼명을 snake_case로 변경

In [39]:
selected_colunms =["NCT Number",
    "Study Title",
    "Study Status",
    "Conditions",
    "Interventions",
    "Sponsor",
    "Phases",
    "Locations",
    "Start Date",
    "Completion Date"]

anxiety_base = anxiety_df[selected_colunms].copy()
anxiety_base.head()

,NCT Number,Study Title,Study Status,Conditions,Interventions,Sponsor,Phases,Locations,Start Date,Completion Date
0,NCT06150612,Unwinding Anxiety for Migraine: Pilot,UNKNOWN,Migraine|Anxiousness,BEHAVIORAL: Unwinding Anxiety,Yeshiva University,NaN,"Rousso Building, The Bronx, New York, 10461, U...",2024-01-03,2025-01-01
1,NCT01675986,Comparing the Efficacy of Pregabalin and Hydro...,COMPLETED,Feeling Anxious,DRUG: hydroxyzine|DRUG: Pregabalin|DRUG: Lactose,Poitiers University Hospital,PHASE2,"CHU de POITIERS, Poitiers, 86021, France",NaN,NaN
2,NCT03425487,Mindfulness-based and Compassion-based Interve...,COMPLETED,Anxious-Depressive,BEHAVIORAL: Mindfulness based Intervention|BEH...,Hospital Miguel Servet,NaN,"Hospital Universitario de la Plana, Castellon,...",2019-01-01,2019-10-31
3,NCT06921512,TCM Daoyin for Anxiety/Depression: Psychologic...,RECRUITING,Anxiety Symptom|Depression Symptom,BEHAVIORAL: TCM Daoyin exercise,Shanghai University of Traditional Chinese Med...,NaN,"Shanghai Qigong Research Institute, Shanghai, ...",2025-04-10,2027-09-30
4,NCT06350201,Machine Learning-based Classification of Sympt...,RECRUITING,Depression and Anxiety Symptom,BEHAVIORAL: problem solving therapy|OTHER: con...,Wuhan Mental Health Centre,NaN,"Renmin Hospital of Wuhan University, Wuhan, China",2025-09-01,2026-12-01

In [40]:
anxiety_base = anxiety_base.rename(columns={
    "NCT Number":"nct_id",
    "Study Title":"study_title",
    "Study Status":"study_status",
    "Conditions": "conditions",
    "Interventions":"interventions",
    "Sponsor":"sponsor",
    "Phases":"phases",
    "Locations":"locations",
    "Start Date":"start_date",
    "Completion Date":"completion_date"
        })
anxiety_base.head()

,nct_id,study_title,study_status,conditions,interventions,sponsor,phases,locations,start_date,completion_date
0,NCT06150612,Unwinding Anxiety for Migraine: Pilot,UNKNOWN,Migraine|Anxiousness,BEHAVIORAL: Unwinding Anxiety,Yeshiva University,NaN,"Rousso Building, The Bronx, New York, 10461, U...",2024-01-03,2025-01-01
1,NCT01675986,Comparing the Efficacy of Pregabalin and Hydro...,COMPLETED,Feeling Anxious,DRUG: hydroxyzine|DRUG: Pregabalin|DRUG: Lactose,Poitiers University Hospital,PHASE2,"CHU de POITIERS, Poitiers, 86021, France",NaN,NaN
2,NCT03425487,Mindfulness-based and Compassion-based Interve...,COMPLETED,Anxious-Depressive,BEHAVIORAL: Mindfulness based Intervention|BEH...,Hospital Miguel Servet,NaN,"Hospital Universitario de la Plana, Castellon,...",2019-01-01,2019-10-31
3,NCT06921512,TCM Daoyin for Anxiety/Depression: Psychologic...,RECRUITING,Anxiety Symptom|Depression Symptom,BEHAVIORAL: TCM Daoyin exercise,Shanghai University of Traditional Chinese Med...,NaN,"Shanghai Qigong Research Institute, Shanghai, ...",2025-04-10,2027-09-30
4,NCT06350201,Machine Learning-based Classification of Sympt...,RECRUITING,Depression and Anxiety Symptom,BEHAVIORAL: problem solving therapy|OTHER: con...,Wuhan Mental Health Centre,NaN,"Renmin Hospital of Wuhan University, Wuhan, China",2025-09-01,2026-12-01

In [41]:
anxiety_base["start_date"] = pd.to_datetime(anxiety_base["start_date"], errors="coerce")
anxiety_base["completion_date"] = pd.to_datetime(anxiety_base["completion_date"], errors="coerce")

anxiety_base.dtypes

nct_id                     object
study_title                object
study_status               object
conditions                 object
interventions              object
sponsor                    object
phases                     object
locations                  object
start_date         datetime64[ns]
completion_date    datetime64[ns]
dtype: object

In [43]:
text_colunms = ['nct_id',
 'study_title',
 'study_status',
 'conditions',
 'interventions',
 'sponsor',
 'phases',
 'locations'
            ]

for col in text_colunms:
    anxiety_base[col] = anxiety_base[col].astype("string").str.strip()

In [46]:
anxiety_base = anxiety_base.replace("",pd.NA)

In [48]:
anxiety_base.head()

,nct_id,study_title,study_status,conditions,interventions,sponsor,phases,locations,start_date,completion_date
0,NCT06150612,Unwinding Anxiety for Migraine: Pilot,UNKNOWN,Migraine|Anxiousness,BEHAVIORAL: Unwinding Anxiety,Yeshiva University,<NA>,"Rousso Building, The Bronx, New York, 10461, U...",2024-01-03,2025-01-01
1,NCT01675986,Comparing the Efficacy of Pregabalin and Hydro...,COMPLETED,Feeling Anxious,DRUG: hydroxyzine|DRUG: Pregabalin|DRUG: Lactose,Poitiers University Hospital,PHASE2,"CHU de POITIERS, Poitiers, 86021, France",NaT,NaT
2,NCT03425487,Mindfulness-based and Compassion-based Interve...,COMPLETED,Anxious-Depressive,BEHAVIORAL: Mindfulness based Intervention|BEH...,Hospital Miguel Servet,<NA>,"Hospital Universitario de la Plana, Castellon,...",2019-01-01,2019-10-31
3,NCT06921512,TCM Daoyin for Anxiety/Depression: Psychologic...,RECRUITING,Anxiety Symptom|Depression Symptom,BEHAVIORAL: TCM Daoyin exercise,Shanghai University of Traditional Chinese Med...,<NA>,"Shanghai Qigong Research Institute, Shanghai, ...",2025-04-10,2027-09-30
4,NCT06350201,Machine Learning-based Classification of Sympt...,RECRUITING,Depression and Anxiety Symptom,BEHAVIORAL: problem solving therapy|OTHER: con...,Wuhan Mental Health Centre,<NA>,"Renmin Hospital of Wuhan University, Wuhan, China",2025-09-01,2026-12-01

In [49]:
before_count = len(anxiety_base)
cleaned_anxiety = anxiety_base.drop_duplicates(subset="nct_id").copy()

In [50]:
after_count = len(cleaned_anxiety)

In [51]:
print("before_count",before_count)
print("after_count",after_count)

before_count 1000
after_count 1000

In [52]:
cleaned_anxiety["phases"] = cleaned_anxiety["phases"].fillna("NO_PHASE")
cleaned_anxiety["phases"].value_counts()

phases
NO_PHASE         711
PHASE3            94
PHASE2            87
PHASE4            55
PHASE1            30
PHASE2|PHASE3     10
EARLY_PHASE1       7
PHASE1|PHASE2      6
Name: count, dtype: Int64

In [53]:
save_path = "../data/cleaned_anxiety_trials.csv"
cleaned_anxiety.to_csv(save_path, index=False)
print("저장완료",save_path)

저장완료 ../data/cleaned_anxiety_trials.csv

In [56]:
check_df = pd.read_csv("../data/cleaned_anxiety_trials.csv")
check_df.shape

(1000, 10)